services:
  rover:
    build:
      context: ../../
      dockerfile: deployment/rover/Dockerfile
    container_name: rover
    restart: unless-stopped
    network_mode: host
    volumes:
      - /dev:/dev
    # volumes:
    #   - ./config:/home/ros/config
    #   - ./logs:/home/ros/logs
  micro-ros-agent:
    image: microros/micro-ros-agent:jazzy
    container_name: micro
    network_mode: host
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0"
    command: serial --dev /dev/ttyACM0